language: c

dist: xenial
sudo: required

compiler:
    - clang
    - gcc

before_install:
    - uname -a
    - cat /etc/issue
    - sudo apt-get update -qq
    - sudo apt-get install libc6-dbg:i386 libc6-dev-i386 valgrind doxygen
    - echo "Packages below for fixing build in Xenial"
    - sudo apt-get install gcc-multilib linux-libc-dev linux-libc-dev:i386

install: true

before_script: true

script:
    - make BIT=32 -j4 && make BIT=32 -j4 check && make BIT=32 -j4 valgrind-check
    - make clean && make BIT=32 SHARED=true -j4 && make BIT=32 SHARED=true -j4 check && make BIT=32 SHARED=true -j4 valgrind-check
    - make clean && make -j4 && make -j4 check && make -j4 valgrind-check
    - make clean && make SHARED=true -j4 && make SHARED=true -j4 check && make SHARED=true valgrind-check

after_success: make doc

after_script:
    - make validate
    - make clean && make -j4 && make bench
    - make clean && make SHARED=true -j4 && make SHARED=true bench
    - make bench-run

after_failure: true

notifications:
    email:
      - hyzwowtools@gmail.com
