language: c

compiler:
    - clang
    - gcc

before_install:
    - uname -a
    - cat /etc/issue
    - sudo apt-get update -qq
    - sudo apt-get install libc6-dbg:i386 libc6-dev-i386 valgrind doxygen

install: true

before_script: true

script:
    - make BIT=32 -j4 && make BIT=32 -j4 check
    - make clean && make BIT=32 SHARED=true -j4 && make BIT=32 SHARED=true -j4 check
    - make clean && make -j4 && make -j4 check && make -j4 valgrind-check
    - make clean && make SHARED=true -j4 && make SHARED=true -j4 check && make SHARED=true valgrind-check

after_script:
    - make validate
    - make clean && make -j4 && make bench
    - make clean && make SHARED=true -j4 && make SHARED=true bench

after_success: make doc

after_failure: true

notifications:
    email:
      - hyzwowtools@gmail.com
